CampCorr/Models/Campeonato.cs
using System.ComponentModel.DataAnnotations;

namespace CampCorr.Models
{
    public class Campeonato
    {
        [Key]
        public int CampeonatoId { get; set; }
        public string UserId { get; set; }
        public byte[] Logo { get; set; }

        public List<Temporada> Temporadas{ get; set; }
        public List<Equipe> Equipes { get; set; }
    }
}

CampCorr/ViewModels/CampeonatoViewModel.cs
using CampCorr.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CampCorr.ViewModels
{
    public class CampeonatoViewModel
    {
        public int IdCampeonato { get; set; }
        [Required(ErrorMessage = "Informe o nome")]
        [Display(Name = "Nome do campeonato")]
        [StringLength(50)]
        public string NomeCampeonato { get; set; }
        public string UserId { get; set; }
        public int TemporadaId { get; set; }
        public int RegulamentoId { get; set; }
        public string Logo { get; set; }
        public string Senha { get; set; }
        public int AnoTemporada { get; set; } = DateTime.Now.Year;
        [Required(ErrorMessage = "Informe quantas etapas terá sua temporada")]
        [Display(Name = "Quantidade de etapas")]
        [Column(TypeName = "Int")]
        public int QuantidadeEtapas { get; set; }
        [Display(Name = "Regras")]
        public string Regulamento { get; set; }
        [Display(Name = "Nome do traçado")]
        public string Traçado { get; set; }
        [Display(Name = "Tipo de circuito")]
        public string Tipo { get; set; }
        [Required(ErrorMessage = "Informe o dia e a hora da corrida")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "0:dd/MM hh:mm")]
        [Display(Name = "Data e hora da corrida")]
        public DateTime Data { get; set; }
        [Display(Name = "Etapa")]
        public string NumeroEvento { get; set; }
        [Display(Name = "Nome do Circuito")]
        public string NomeCircuito { get; set; }
        public List<Circuito> Circuitos { get; set; }
        public List<Temporada> Temporadas { get; set; }
        public List<Etapa> Etapas { get; set; }

        public CampeonatoViewModel() { }
        public CampeonatoViewModel(int campeonatoId, string userId, string userName, string logo)
        {
            this.IdCampeonato = campeonatoId;
            this.UserId = userId;
            this.NomeCampeonato = userName;
            this.Logo = logo;
        }

    }
}

CampCorr/Areas/Admin/Controllers/CampeonatosController.cs
using Microsoft.AspNetCore.Mvc;
using CampCorr.Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using CampCorr.Models;
using ReflectionIT.Mvc.Paging;
using CampCorr.ViewModels;
using Microsoft.AspNetCore.Identity;
using CampCorr.Repositories;
using CampCorr.Repositories.Interfaces;
using MockQueryable.Moq;
using CampCorr.Services.Interfaces;
using Microsoft.AspNetCore.Hosting;

namespace CampCorr.Areas.Campeonato.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Adm")]
    public class CampeonatosController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ICampeonatoService _campeonatoService;
        private readonly IUsuarioService _usuarioService;
        private readonly ITemporadaService _temporadasService;
        private readonly IPilotoService _pilotoService;
        private readonly string nomeUsuario;
        private readonly int campeonatoId;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IUtilitarioService _utilitarioService;
        public CampeonatosController(SignInManager<IdentityUser> signInManager, ICampeonatoService icampeonatoService, IUsuarioService usuarioService, ITemporadaService temporadasService, IPilotoService pilotoService, IWebHostEnvironment webHostEnvironment, IUtilitarioService utilitarioService)
        {
            _signInManager = signInManager;
            nomeUsuario = signInManager.Context.User.Identity.Name;
            _campeonatoService = icampeonatoService;
            _usuarioService = usuarioService;
            _temporadasService = temporadasService;
            _pilotoService = pilotoService;
            campeonatoId = _campeonatoService.BuscarIdCampeonato(nomeUsuario);
            _webHostEnvironment = webHostEnvironment;
            _utilitarioService = utilitarioService;
        }


        //public IActionResult Index()
        //{
        //    return View();
        //}

        //public IActionResult Create()
        //{
        //    ViewData["CampeonatoId"] = new SelectList(_context.Campeonatos, "CampeonatoId", "CampeonatoName");
        //    return View();
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Create([Bind("CampeonatoId,NomeCampeonato,Logo,Senha")] LoginCampeonatoViewModel campeonatoVm)
        //{
        //    if (ModelState.IsValid)
        //    {
        //         Usar repositório para gravar no banco
        //        _campeonatoRepository.Salvar(campeonatoVm);
        //        return RedirectToAction("Create", "Temporadas", new { campeonatoVm/*.CampeonatoId */});
        //    }
        //    return View(campeonatoVm);
        //}

        public async Task<IActionResult> Edit()
        {
            var campeonatoId = _campeonatoService.BuscarIdCampeonato(nomeUsuario);
            var userId = _usuarioService.BuscarIdUsuario(nomeUsuario);


            var campeonato = await _campeonatoService.BuscarCampeonato(campeonatoId);
            if (campeonato == null)
            {
                return NotFound();
            }
            CampeonatoViewModel campeonatoVM = new CampeonatoViewModel(campeonato.CampeonatoId, campeonato.UserId, nomeUsuario, _utilitarioService.MontaImagem(campeonato.Logo));
            if (campeonato.Logo != null && campeonato.Logo.Length > 0)
            {
                ViewBag.Logo = _utilitarioService.MontaImagem(campeonato.Logo);
            }
            campeonatoVM.Temporadas = _temporadasService.ListarTemporadasDoCampeonato(campeonatoId);

            return View(campeonatoVM);
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormFile logo, [Bind("IdCampeonato,Logo,NomeCampeonato")] CampeonatoViewModel campeonatoVm)
        {
            Models.Campeonato campeonato = await _campeonatoService.BuscarCampeonato(campeonatoVm.IdCampeonato);
            if (logo != null && logo.Length > 0)
            {
                campeonato.Logo = _utilitarioService.PreparaImagem(logo);
            }
            campeonatoVm.NomeCampeonato = nomeUsuario;

            if (ModelState.IsValid)
            {
                _campeonatoService.Atualizar(campeonato);

                CampeonatoViewModel campeonatoVM = new CampeonatoViewModel(campeonato.CampeonatoId, campeonato.UserId, nomeUsuario, _utilitarioService.MontaImagem(campeonato.Logo));
                campeonatoVM.Temporadas = _temporadasService.ListarTemporadasDoCampeonato(campeonato.CampeonatoId);
                if (campeonato.Logo != null && campeonato.Logo.Length > 0)
                {
                    campeonatoVM.Logo = _utilitarioService.MontaImagem(campeonato.Logo);
                }
                return View(campeonatoVM);
            }
            return View(campeonatoVm);
        }

        public async Task<IActionResult> BuscarPilotos(PilotoViewModel filtro, int pageindex = 1, string sort = "UserLogin")
        {
            List<PilotoViewModel> listaPilotoVm = MontarListaPilotoVmCampeonato();


            var resultado = listaPilotoVm.AsQueryable();

            string nomePiloto = String.IsNullOrEmpty(filtro.NomePiloto) ? "" : filtro.NomePiloto;
            string userLogin = String.IsNullOrEmpty(filtro.UserLogin) ? "" : filtro.UserLogin;

            if (!string.IsNullOrEmpty(filtro.UserLogin) || !string.IsNullOrEmpty(filtro.NomePiloto))
                resultado = resultado.Where(p => p.UserLogin.Contains(userLogin) && p.NomePiloto.Contains(nomePiloto));

            resultado = resultado.BuildMockDbSet().Object;

            var model = await PagingList.CreateAsync(resultado, 10, pageindex, sort, "UserLogin");
            model.RouteValue = new RouteValueDictionary { { "filtro.UserLogin", filtro.UserLogin } };
            return View(model);
        }

        public async Task<IActionResult> AddPilotoCampeonato(int pilotoId, [Bind("Id, PilotoId,CampeonatoId")] PilotoCampeonato pilotoCampeonato)
        {

            if (ModelState.IsValid)
            {
                pilotoCampeonato.PilotoId = pilotoId;
                pilotoCampeonato.CampeonatoId = _campeonatoService.BuscarIdCampeonato(nomeUsuario);
                _pilotoService.SalvarPilotoCampeonato(pilotoCampeonato);
            }

            var listaPilotoVm = MontarListaPilotoVmCampeonato();
            var resultado = listaPilotoVm.AsQueryable();
            resultado = resultado.BuildMockDbSet().Object;
            var model = await PagingList.CreateAsync(resultado, 5, 1, "UserLogin", "UserLogin");
            return RedirectToAction("BuscarPilotos", model);
        }
        public ActionResult VisualizarPilotosCampeonato()
        {
            var pilotosCampeonato = _pilotoService.ListarPilotosVmCampeonato(campeonatoId);

            return View(pilotosCampeonato);
        }
        public ActionResult RemovePilotoCampeonato(int pilotoId)
        {
            var idCampeonato = campeonatoId;
            _pilotoService.RemovePilotoCampeonato(pilotoId, idCampeonato);


            var listaPilotosCampeonato = _pilotoService.ListarPilotosVmCampeonato(idCampeonato);
            return View("VisualizarPilotosCampeonato", listaPilotosCampeonato);
        }

        private List<PilotoViewModel> MontarListaPilotoVmCampeonato()
        {
            List<PilotoViewModel> listaPilotoVm = new List<PilotoViewModel>();
            var listaUsuario = _usuarioService.ListarUsuarios();
            var listaPilotos = _pilotoService.ListarPilotos();
            var listaPilotosCadastrados = _pilotoService.ListarPilotosCampeonato();
            foreach (var item in listaUsuario)
            {
                var piloto = listaPilotos.Where(x => x.UsuarioId == item.Id).FirstOrDefault();
                if (piloto != null)
                {
                    var pilotoCadastrado = listaPilotosCadastrados
                        .Where(x => x.PilotoId == piloto.PilotoId && x.CampeonatoId == campeonatoId)
                        .FirstOrDefault();
                    if (pilotoCadastrado == null)
                    {
                        listaPilotoVm.AddRange(new[]
                        {
                            new PilotoViewModel(piloto.PilotoId, item.UserName, piloto.Nome)
                        });
                    }
                }
            }
            return listaPilotoVm;
        }
    }
}

CampCorr/Areas/Admin/Views/Campeonatos/BuscarPilotos.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<CampCorr.ViewModels.PilotoViewModel>
@{
    Model.Action = "BuscarPilotos";
    var filtro = new PilotoViewModel();
}

<h2 class="fw-bold mb-2 text-uppercase">Pilotos</h2>
<p class="text-white-50 mb-5">Busque pelo piloto para adiciona-lo ao campeonato</p>

<div class="form-outline form-white mb-4">
    <form method="get" class="form-inline">
        <div class="form-group">
            <label asp-for="@filtro.UserLogin" class="control-label"></label>
            <input asp-for="@filtro.UserLogin" class="form-control" placeholder="Digite o Usuário do piloto" />
        </div>
        <div class="form-group">
            <label asp-for="@filtro.NomePiloto" class="control-label"></label>
            <input asp-for="@filtro.NomePiloto" class="form-control" placeholder="Digite o nome do piloto" />
        </div>
        <div class="form-outline mb-5" style="margin-top: 3%">
            <button type="submit" class="btn btn-secondary btn-lg px-5">
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Buscar
            </button>
        </div>
    </form>
</div>

<div> Total de pilotos : @Model.TotalRecordCount </div>
<div>
    <vc:pager paging-list="@Model" asp-page="@Model.Action"></vc:pager>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table text-white">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.NomePiloto)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.UserLogin)
                    </th>
                    <th>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NomePiloto)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserLogin)
                        </td>

                        <td>
                            <a asp-action="AddPilotoCampeonato" asp-route-pilotoId="@item.PilotoId" class="btn btn-secondary">Adicionar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>
<div>
    <a asp-action="VisualizarPilotosCampeonato" asp-controller="Campeonatos">Voltar</a>
</div>

CampCorr/Areas/Admin/Views/Campeonatos/Create.cshtml
@model CampCorr.ViewModels.CampeonatoViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

<h4>Campeonato</h4>

<hr />

<div class="form-outline form-white mb-4">
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="NomeCampeonato" class="control-label"></label>
            <input asp-for="NomeCampeonato" class="form-control" />
            <span asp-validation-for="NomeCampeonato" class="text-danger"></span>
        </div>
        @*<div class="form-group">
            <label asp-for="Logo" class="control-label"></label>
            <input asp-for="Logo" class="form-control" />
            <span asp-validation-for="Logo" class="text-danger"></span>
        </div>*@
        <div class="form-group">
            <label asp-for="Senha" class="control-label"></label>
            <input asp-for="Senha" class="form-control" />
            <span asp-validation-for="Senha" class="text-danger"></span>
        </div>
        <hr />
        <div class="form-group">
            <input type="submit" value="Configurar Temporada" class="btn btn-primary" />
        </div>
    </form>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

CampCorr/Areas/Admin/Views/Campeonatos/Edit.cshtml
@model CampCorr.ViewModels.CampeonatoViewModel

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Campeonato</h4>

<hr />

<div class="form-outline form-white mb-4">
    <form asp-action="Edit" enctype="multipart/form-data" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="IdCampeonato" value="@Model.IdCampeonato" />
        <input type="hidden" asp-for="NomeCampeonato" value="@Model.NomeCampeonato" />
        <div class="form-group">
            <label asp-for="NomeCampeonato" class="control-label"></label>
            @*<span class="form-control">@Model.NomeCampeonato</span>*@
            <h3>@Model.NomeCampeonato</h3>

            <span asp-validation-for="NomeCampeonato" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Logo" class="control-label"></label>
            @if (Model.Logo == null)
            {
                <div class="form-group">
                    <input type="file" name="logo" class="form-control-file " />
                </div>
            }
            else
            {
                <img src="@Model.Logo" alt="Imagem" width="100" height="72" />
                <hr />
                <div>
                    ALterar logo
                </div>
                <div class="form-group">
                    <input type="file" name="logo" class="form-control-file " />
                </div>
            }
            <span asp-validation-for="Logo" class="text-danger"></span>
        </div>
        <hr />
        <div class="form-group">
            <a asp-action="VisualizarPilotosCampeonato" asp-controller="Campeonatos" class="botaoNavegacao btn">Pilotos do Campeonato</a>
        </div>

        <hr />
        <div class="form-group">
            <input type="submit" value="Salvar" class="btn btn-primary" />
        </div>
        <hr />
        @if (Model.Temporadas.Count() > 0)
        {
            <div>
                Editar temporada
            </div>
            <div>
                @foreach (var item in Model.Temporadas)
                {
                    <a class="btn btn-secondary btn-block" asp-action="Edit" asp-controller="Temporadas" asp-route-ano="@item.AnoTemporada">
                        @item.AnoTemporada.ToString()
                    </a>
                }
            </div>
        }
        else
        {
            <div>
                <a asp-action="Create" asp-area="Admin" asp-controller="Temporadas"> Adicionar temporada </a>
            </div>
        }


    </form>
</div>


<div>
    <a asp-action="Index" asp-area="" asp-controller="Home">Voltar a página inicial</a>
</div>
@section scripts{
    <script>
        $(document).ready(function() {
            
        });




    </script>
}

CampCorr/Areas/Admin/Views/Campeonatos/Index.cshtml
@model CampCorr.ViewModels.CampeonatoViewModel

@{
    ViewData["Title"] = "Editar";
}

<h1>Pagina de administração de campeonatos</h1>

<h4>@Model.NomeCampeonato</h4>

<hr />

<div class="form-outline form-white mb-4">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="IdCampeonato" />
        <div class="form-group">
            <label asp-for="NomeCampeonato" class="control-label"></label>
            <input asp-for="NomeCampeonato" class="form-control" />
            <span asp-validation-for="NomeCampeonato" class="text-danger"></span>
        </div>
        @*<div class="form-group">
            <label asp-for="Logo" class="control-label"></label>
            <input asp-for="Logo" class="form-control" />
            <span asp-validation-for="Logo" class="text-danger"></span>
        </div>*@
        
        <hr />
        <div class="form-group">
            <input type="submit" value="Salvar" class="btn btn-primary" />
        </div>
        <hr />
        @*@if (true)
        {
            <div>
                Editar temporada
            </div>
            @foreach (var item in Model.Temporada)
            {
                <div>
                    <a asp-action="Edit" asp-controller="Temporadas" asp-route-temporadaId="@item.TemporadaId">
                        @item.AnoTemporada.ToString()
                    </a>
                </div>
            }
        }
        else
        {
            <div>
                Adicionar temporada
            </div>
        }*@

            
    </form>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

CampCorr/Areas/Admin/Views/Campeonatos/VisualizarPilotosCampeonato.cshtml
@model IEnumerable<CampCorr.ViewModels.PilotoViewModel>

<h2 class="fw-bold mb-2 text-uppercase">Pilotos</h2>
<hr />
<h4>Pilotos já adicionados no campeonato(@Model.Count()) </h4>
<a class="btn btn-secondary" asp-action="BuscarPilotos">Adicionar novos pilotos</a>
<div class="row">
    <div class="col-md-12">
        <table class="table text-white">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.NomePiloto)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.UserLogin)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.OrderBy(x => x.NomePiloto))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NomePiloto)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserLogin)
                        </td>

                        <td>
                            <a asp-action="RemovePilotoCampeonato" asp-route-pilotoId="@item.PilotoId" class="btn btn-danger">Remover</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>



<div>
    <a asp-action="Edit" asp-controller="Campeonatos">Voltar</a>
</div>