CampCorr/Models/Temporada.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CampCorr.Models
{
    public class Temporada
    {
        public int TemporadaId { get; set; }
        public int AnoTemporada { get; set; } = DateTime.Now.Year;
        [Required(ErrorMessage = "Informe quantas etapas terá sua temporada")]
        [Display(Name = "Quantidade de etapas")]
        [Column(TypeName = "Int")]
        public int QuantidadeEtapas { get; set; }
        public int CampeonatoId { get; set; }
        public int RegulamentoId { get; set; }
        public bool Concluida { get; set; }
        public virtual Campeonato Campeonato { get; set; }
        public virtual Regulamento Regulamento { get; set; }
        //TODO Remover listas e adicionar ViewModel para trabalhar essas listas
        public List<Etapa> Etapas { get; set; }
        public List<Piloto> Pilotos { get; set; }
        public List<Equipe> Equipes { get; set; }
    }
}

CampCorr/Areas/Admin/Controllers/TemporadasController.cs
using Microsoft.AspNetCore.Mvc;
using CampCorr.Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using CampCorr.Models;
using CampCorr.Repositories.Interfaces;
using Microsoft.AspNetCore.Identity;
using CampCorr.ViewModels;
using CampCorr.Services.Interfaces;

namespace CampCorr.Areas.Campeonato.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Adm")]
    public class TemporadasController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ICampeonatoService _campeonatoService;
        private readonly ITemporadaService _temporadaService;
        private readonly IEtapaService _etapaService;
        private readonly ICircuitoService _circuitoService;
        private readonly IRegulamentoService _regulamentoService;
        private readonly IPilotoService _pilotoService;
        private readonly IUsuarioService _usuarioService;
        private readonly string nomeUsuario;
        private readonly int campeonatoId;

        public TemporadasController(SignInManager<IdentityUser> signInManager, ICampeonatoService campeonatoService, ITemporadaService temporadasService, IEtapaService etapaService, ICircuitoService circuitoService, IRegulamentoService regulamentoService, IPilotoService pilotoService, IUsuarioService usuarioService)
        {
            _signInManager = signInManager;
            nomeUsuario = signInManager.Context.User.Identity.Name;
            _campeonatoService = campeonatoService;
            campeonatoId = _campeonatoService.BuscarIdCampeonato(nomeUsuario);
            _temporadaService = temporadasService;
            _etapaService = etapaService;
            _circuitoService = circuitoService;
            _regulamentoService = regulamentoService;
            _pilotoService = pilotoService;
            _usuarioService = usuarioService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            ViewBag.Regulamentos = _regulamentoService.ListarRegulamentos().ToList();
            TempData["campeonatoId"] = campeonatoId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("TemporadaId,QuantidadeEtapas,RegulamentoId")] Temporada temporada)
        {
            temporada.CampeonatoId = campeonatoId;
            if (ModelState.IsValid)
            {
                _temporadaService.Salvar(temporada);
                return RedirectToAction("Edit", new { ano = temporada.AnoTemporada });
            }
            return View(temporada);
        }

        public async Task<IActionResult> Edit(int ano)
        {
            ViewBag.Regulamentos = _regulamentoService.ListarRegulamentos();
            var temporada = await _temporadaService.BuscarTemporadaAsync(campeonatoId, ano);
            if (temporada == null)
            {
                return NotFound();
            }

            temporada.Etapas = _etapaService.ListarEtapasTemporada(temporada.TemporadaId);
            foreach (var item in temporada.Etapas)
            {
                item.Circuito = await _circuitoService.BuscarCircuitoAsync(item.CircuitoId);
            }
            CampeonatoViewModel campeonatoTemporadaVm = new CampeonatoViewModel()
            {
                Etapas = temporada.Etapas.OrderBy(x => x.Data).ToList(),
                AnoTemporada = temporada.AnoTemporada,
                QuantidadeEtapas = temporada.QuantidadeEtapas,
                Regulamento = _regulamentoService.BuscarRegulamento(temporada.RegulamentoId).Nome,
                RegulamentoId = temporada.RegulamentoId,
                TemporadaId = temporada.TemporadaId
                
            };

            return View(campeonatoTemporadaVm);
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("TemporadaId,QuantidadeEtapas,RegulamentoId")] Temporada temporada)
        {
            ViewBag.Regulamentos = _regulamentoService.ListarRegulamentos();

            temporada.CampeonatoId = _campeonatoService.BuscarIdCampeonato(nomeUsuario);

            if (ModelState.IsValid)
            {
                try
                {
                    _temporadaService.Atualizar(temporada);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! _temporadaService.TemporadaExists(temporada.CampeonatoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                temporada.Etapas = _etapaService.ListarEtapasTemporada(temporada.TemporadaId);
                foreach (var item in temporada.Etapas)
                {
                    item.Circuito = await _circuitoService.BuscarCircuitoAsync(item.CircuitoId);
                }
                CampeonatoViewModel campeonatoTemporadaVm = new CampeonatoViewModel()
                {
                    Etapas = temporada.Etapas.OrderBy(x => x.Data).ToList(),
                    AnoTemporada = temporada.AnoTemporada,
                    QuantidadeEtapas = temporada.QuantidadeEtapas,
                    Regulamento = _regulamentoService.BuscarRegulamento(temporada.RegulamentoId).Nome
                };
                return View(campeonatoTemporadaVm);
            }
            return View(temporada);
        }

        public async Task<IActionResult> VisualizarPilotosTemporada(int anoTemporada)
        {
            TempData["anoTemporada"] = anoTemporada;

            var temporada = await _temporadaService.BuscarTemporadaAsync(campeonatoId, anoTemporada);
            var pilotosCampeonato = _pilotoService.ListarPilotosDoCampeonato(temporada.CampeonatoId);

            List<PilotoViewModel> listaPilotoCampeonatoVM = new List<PilotoViewModel>() { };
            foreach (var piloto in pilotosCampeonato)
            {
                var nomeUsuario = await _usuarioService.BuscarUsuarioAsync(piloto.UsuarioId);
                PilotoViewModel pilotoVM = new PilotoViewModel()
                {
                    NomePiloto = piloto.Nome,
                    PilotoId = piloto.PilotoId,
                    UserLogin = nomeUsuario.UserName,
                };
                listaPilotoCampeonatoVM.Add(pilotoVM);
            }
            var listaPilotosTemporadaAdicionado = _pilotoService.ListarPilotosVmTemporada(temporada.TemporadaId);
            var listaPilotosTemporadaNaoAdicionado = _pilotoService.ListarPilotosVmSemTemporada(listaPilotoCampeonatoVM, listaPilotosTemporadaAdicionado);

            ViewBag.ListaPilotosCampeonato = listaPilotoCampeonatoVM;
            ViewBag.ListaPilotosTemporadaAdicionado = listaPilotosTemporadaAdicionado;
            ViewBag.ListaPilotosTemporadaNaoAdicionado = listaPilotosTemporadaNaoAdicionado;

            return View(listaPilotoCampeonatoVM);
        }
        [HttpPost]
        public async Task<JsonResult> PostAddPilotos(List<string> idPiloto, int anoTemporada, [Bind("Id,PilotoId,TemporadaId")] PilotoTemporada pilotoTemporada)
        {
            var temporadaId = await _temporadaService.BuscarIdTemporadaAsync(nomeUsuario, anoTemporada);
            if (ModelState.IsValid)
            {
                foreach (var id in idPiloto)
                {
                    pilotoTemporada.Id = 0;
                    pilotoTemporada.TemporadaId = temporadaId;
                    pilotoTemporada.PilotoId = Convert.ToInt32(id);
                    _pilotoService.SalvarPilotoTemporada(pilotoTemporada);
                }
            }
            return new JsonResult(Ok());
        }
        [HttpPost]
        public async Task<JsonResult> PostRemoverPilotos(List<string> idPiloto, int anoTemporada)
        {
            var temporadaId = await _temporadaService.BuscarIdTemporadaAsync(nomeUsuario, anoTemporada);
            foreach (var id in idPiloto)
            {
                var pilotorRemover = await _pilotoService.BuscarPilotoTemporadaAsync(Convert.ToInt32(id), temporadaId);
                if (pilotorRemover != null)
                {
                    _pilotoService.RemoverPilotoTemporada(pilotorRemover);
                }
            }
            return new JsonResult(Ok());
        }

        
    }
}

CampCorr/Areas/Admin/Views/Temporadas/Create.cshtml
@model CampCorr.Models.Temporada

@{
    ViewData["Title"] = "Create";
    var listaRegulamentos = ViewBag.Regulamentos;
}

<h1>Adicionar</h1>

<h4>Temporada</h4>

<hr />

<div class="form-outline form-white mb-4">
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="QuantidadeEtapas" class="control-label"></label>
            <input asp-for="QuantidadeEtapas" class="form-control" />
            <span asp-validation-for="QuantidadeEtapas" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label class="control-label">Selecione o regulamento</label>
            @Html.DropDownList("RegulamentoId", new SelectList(listaRegulamentos, "RegulamentoId", "Nome"), new {@class = "form-select"})
            <span asp-validation-for="RegulamentoId" class="text-danger"></span>
        </div>
        <hr />

        <div class="form-group">
            <input type="submit" value="Salvar" class="btn btn-primary" />
        </div>
    </form>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

CampCorr/Areas/Admin/Views/Temporadas/Edit.cshtml
@model CampCorr.ViewModels.CampeonatoViewModel

@{
    ViewData["Title"] = "Editar";
    var temporadaId = Model.TemporadaId;
    var listaRegulamentos = ViewBag.Regulamentos;
}

<h1>Editar</h1>

<h4>Temporada</h4>

<hr />

<div class="form-outline form-white mb-4">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="TemporadaId" value=@Model.TemporadaId/>
        <div class="form-group">
            <label asp-for="AnoTemporada" class="control-label"></label>
            <input disabled class="form-control" value="@Model.AnoTemporada"/>
            <span asp-validation-for="AnoTemporada" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="QuantidadeEtapas" class="control-label"></label>
            <input asp-for="QuantidadeEtapas" class="form-control" />
            <span asp-validation-for="QuantidadeEtapas" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Regulamento" class="control-label"></label>
            @Html.DropDownList("RegulamentoId", new SelectList(listaRegulamentos, "RegulamentoId", "Nome"), @Model.RegulamentoId.ToString(), new { @class = "form-select" })

            @*@Html.DropDownList("RegulamentoId", new SelectList(listaRegulamentos, "RegulamentoId", "Nome"), @Model.Regulamento ,new {@class = "form-select"})*@
            <span asp-validation-for="RegulamentoId" class="text-danger"></span>
        </div>
        <hr />
        <div class="form-group">
            <a asp-action="VisualizarPilotosTemporada" asp-route-anoTemporada="@Model.AnoTemporada" value="Vizualizar Pilotos" style="margin-top:2%" class="botaoNavegacao btn" >Pilotos da temporada</a>
            <a asp-action="VisualizarEquipes" asp-controller="Equipes" asp-route-anoTemporada="@Model.AnoTemporada" value="Visualizar Equipes" style="margin-top:2%" class="btn botaoNavegacao" >Equipes da temporada</a>
        </div>
        
        <div class="form-group" >
            <a asp-action="AdicionarPilotosEquipe" asp-controller="Equipes" asp-route-anoTemporada="@Model.AnoTemporada" value="Visualizar Equipes" class="btn botaoNavegacao" >Adicionar pilotos nas equipes</a>
        </div>
        <hr />
        <div class="form-group">
            <input type="submit" value="Salvar" class="btn btn-primary  col-4" />
        </div>
        <hr />
        @if (Model.Etapas.Count() > 0)
        {
            <div>
                Editar Etapa
            </div>
            @foreach (var item in Model.Etapas)
            {
                <div class="alert alert-etapa">
                    <a class="btn" style="color:azure" asp-action="Edit" asp-controller="Etapas" asp-route-numeroEtapa="@item.NumeroEvento.Substring(0,1)" asp-route-ano="@item.Data.Year">
                        @item.NumeroEvento.ToString()
                        @item.Data.ToShortDateString()
                        @item.Circuito.Nome.ToString()
                    </a>
                </div>
            }
        }
        @if (Model.QuantidadeEtapas > Model.Etapas.Count())
        {
            <div>
                <a asp-action="Create" asp-area="Admin" asp-controller="Etapas" asp-route-anoTemporada="@Model.AnoTemporada"> Adicionar Etapa </a>
            </div>
        }


    </form>
</div>


<div>
    <a asp-action="Edit" asp-controller="Campeonatos">Voltar a lista de temporadas</a>
</div>

CampCorr/Areas/Admin/Views/Temporadas/VisualizarPilotosTemporada.cshtml
@model IEnumerable<CampCorr.ViewModels.PilotoViewModel>
@{
    ViewData["Title"] = "Visualizar Pilotos";
    List<PilotoViewModel> ListaPilotosCampeonato = ViewBag.ListaPilotosCampeonato;
    List<PilotoViewModel> ListaPilotosTemporadaAdicionado = ViewBag.ListaPilotosTemporadaAdicionado;
    List<PilotoViewModel> ListaPilotosTemporadaNaoAdicionado = ViewBag.ListaPilotosTemporadaNaoAdicionado;
    int n = 0;
}

<h1>Selecione os pilotos</h1>

<hr />
<h4 class="cabecalho-sombra">Pilotos do Campeonato disponíveis</h4>
<div class="form-outline">
    @if (ListaPilotosCampeonato.Count() != 0)
    {
        <ul>
            @foreach (var item in ListaPilotosTemporadaNaoAdicionado)
            {
                <li class="lista-item">
                    <input class="form-check-input" name="check-list-AddPiloto" type="checkbox" value="@item.PilotoId">
                    @Html.DisplayFor(x => item.NomePiloto)
                </li>
            }
        </ul>
        <div class="form-group">
            <button onclick="AddPilotos(@TempData["anoTemporada"])" class="btn btn-secondary">Adicionar</button>
        </div>
    }
    else
    {
        <div>
            <h6 class="text-info">Não Existem pilotos disponíveis!!!</h6>
        </div>
    }
</div>



<h4 class="cabecalho-sombra">Pilotos da temporada @TempData["anoTemporada"]</h4>
@if (ListaPilotosTemporadaAdicionado.Count() != 0)
{
    <ul>
        @foreach (var item in ListaPilotosTemporadaAdicionado)
        {
            <li class="lista-item">
                <input class="form-check-input" name="check-list-RemoverPilotos" type="checkbox" value="@item.PilotoId">
                @Html.DisplayFor(x => ListaPilotosTemporadaAdicionado[n].NomePiloto)
                @{
                    n++;
                }
            </li>
        }
    </ul>
    <button onclick="RemoverPilotos(@TempData["anoTemporada"])" name="check-list-RemoverPilotos" class="btn btn-secondary">Remover Pilotos</button>
}
else
{
    <h6 class="text-info">Nenhum piloto adicionado até o momento</h6>
}

<hr />
<div>
    <a asp-action="Edit" asp-controller="Temporadas" asp-route-ano="@TempData["anoTemporada"]">Voltar a lista de temporadas</a>
</div>

@section scripts{
    <script>

        function AddPilotos(anoTemporada) {
            var ids = [];
            $('input[name="check-list-AddPiloto"]:checked').each(function() {
                ids.push(this.value);
            });
            pilotosAdd("@Url.Action("PostAddPilotos")", ids, anoTemporada)
        }
        function RemoverPilotos(anoTemporada) {
            var ids = []
            $('input[name="check-list-RemoverPilotos"]:checked').each(function() {
                ids.push(this.value);
            });
            pilotosRemover("@Url.Action("PostRemoverPilotos")", ids, anoTemporada)
        }
    </script>
    }